name: Main

on:
  push:
    branches: [master, master-dev]
  pull_request:
    branches: [master, master-dev]
  workflow_dispatch:

jobs:
  BuildDesktop:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            artifactName: Z-Slice.0.0.1.windows
            setupScript: .\"setup/windows.bat"
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            setupScript: sh ./setup/unix.sh
            artifactName: Z-Slice.0.0.1.linux
            artifactPath: export/release/linux/bin/*
          - name: macOS x86_64
            os: macos-14
            buildArgs: "mac -64 -D HXCPP_M64"
            setupScript: sh ./setup/mobile.sh
            artifactName: Z-Slice.0.0.1.macosx64
            artifactPath: export/release/macos/bin/*
          - name: macOS AArch64
            os: macos-15
            buildArgs: mac
            setupScript: sh ./setup/mobile.sh
            artifactName: Z-Slice.0.0.1.macos-applesilicon
            artifactPath: export/release/macos/bin/*
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      setupScript: ${{ matrix.setupScript }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
  BuildMobile:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android"
            setupScript: sh ./setup/mobile.sh
            artifactName: Z-Slice.0.0.1.android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            setupScript: sh ./setup/mobile.sh
            artifactName: Z-Slice.0.0.1.ios
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      setupScript: ${{ matrix.setupScript }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
